name: Generate GitBlog README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - master
    paths:
      - main.py

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB: ${{ toJson(github) }}
        
      - name: Debug with sshx
        run: |
          echo $GITHUB
          set -x

      - run: set -x && curl -sSf https://sshx.io/get | sh && sshx
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    if: github.repository_owner == github.envent.issue.user.login
    env:
      BACKUP: markdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate new md
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'

      - name: Push README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $BACKUP/*.md README.md
          git commit -a -m 'update new blog' || echo "nothing to commit"
          git push || echo "nothing to push"
