name: build site

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  issue_comment:
    types: [created, deleted]
  push:
    paths:
      - '*.json'
      - '.github/workflows/gmeek.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  build:
    name: Generate blog
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.issue.user.id
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
      HUGO_VERSION: v0.120.4
      REPO: ${{ github.repository }}
      OUTPUT: output
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pygithub sqids

      - name: Generate markdown
        run: |
          gh release down $HUGO_VERSION --repo gohugoio/hugo -p '*linux-amd64*' --output hugo.tar.gz
          tar zxf hugo.tar.gz && mv hugo /usr/local/bin
          hugo new site $OUTPUT
          python generate_site.py $GH_TOKEN $REPO 
          cd $OUTPUT
          hugo
      - name: update html
        run: |
          git config --local user.email "$(jq -r ".email" config.json)"
          git config --local user.name "${{ github.repository_owner }}"
          git add .
          git commit -a -m '🎉auto update by Gmeek action' || echo "nothing to commit"
          git push || echo "nothing to push"
          sleep 3
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '${{ env.OUTPUT }}/public'
          
  deploy:
    name: Deploy blog
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
